name: moonie
description: "AI playground"
publish_to: 'none'
version: 0.1.0+3

environment:
  sdk: ^3.5.4

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  dio: ^5.7.0
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  # flutter_markdown doesn't allow multi-line selection???
  flutter_markdown_selectionarea: ^0.6.17+1
  # 9.2.2 has a bug with windows - will corrupt the secure storage file
  flutter_secure_storage: ^8.1.0
  langchain: ^0.7.7+1
  langchain_openai: ^0.7.2+5
  provider: ^6.1.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
