name: moonie
description: "AI playground"
publish_to: 'none'
version: 0.2.0+4

environment:
  sdk: ^3.5.4

dependencies:
  async: ^2.11.0
  beautiful_soup_dart: ^0.3.0
  build_runner: ^2.4.13
  collection: ^1.18.0
  cookie_jar: ^4.0.8
  croppy: ^1.3.1
  crypto: ^3.0.6
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  # flutter_markdown doesn't allow multi-line selection???
  flutter_markdown_selectionarea: ^0.6.17+1
  # 9.2.2 has a bug with windows - will corrupt the secure storage file
  flutter_secure_storage: ^8.1.0
  fuzzywuzzy: ^1.2.0
  image_compression_flutter: ^1.0.4
  intl: ^0.19.0
  langchain: ^0.7.7+1
  langchain_openai: ^0.7.2+5
  objectbox: ^4.0.3
  path: ^1.9.0
  path_provider: ^2.1.5
  png_chunks_extract: ^1.0.2
  provider: ^6.1.2
  rhttp: ^0.9.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/prompts/
